name: Release lib-ml

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Update version in setup.py
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          sed -i "s/version=\"[0-9]*\.[0-9]*\.[0-9]*\"/version=\"$VERSION\"/g" setup.py
          cat setup.py

      - name: Build package
        run: |
          pip install build
          python -m build

      - name: Publish to GitHub Packages
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Update to pre-release version
        if: github.repository_owner == 'remla25-team14'
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          NEXT_VERSION=$(echo $VERSION | awk -F. '{$NF = $NF + 1;} 1' OFS=.)
          sed -i "s/version=\"$VERSION\"/version=\"$NEXT_VERSION-pre\"/g" setup.py
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add setup.py
          git commit -m "Bump version to $NEXT_VERSION-pre [skip ci]"
          git push origin HEAD:main 